// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gVtu63v8-2oJAJWjn0T92GZPhRBitZY',
    appId: '1:1020736520203:web:75ddae4327e1792e16470e',
    messagingSenderId: '1020736520203',
    projectId: 'mynotes-midcel',
    authDomain: 'mynotes-midcel.firebaseapp.com',
    storageBucket: 'mynotes-midcel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB407EVvDVQue-gNmaIwEDgBmpvuJrqopQ',
    appId: '1:1020736520203:android:5da8dc20e63fc07516470e',
    messagingSenderId: '1020736520203',
    projectId: 'mynotes-midcel',
    storageBucket: 'mynotes-midcel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7D2F5nCmbo9QryNmAGoZT--8H-rDN2cs',
    appId: '1:1020736520203:ios:b0633eabcfdc09ca16470e',
    messagingSenderId: '1020736520203',
    projectId: 'mynotes-midcel',
    storageBucket: 'mynotes-midcel.firebasestorage.app',
    iosBundleId: 'com.midcel.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7D2F5nCmbo9QryNmAGoZT--8H-rDN2cs',
    appId: '1:1020736520203:ios:b0633eabcfdc09ca16470e',
    messagingSenderId: '1020736520203',
    projectId: 'mynotes-midcel',
    storageBucket: 'mynotes-midcel.firebasestorage.app',
    iosBundleId: 'com.midcel.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5gVtu63v8-2oJAJWjn0T92GZPhRBitZY',
    appId: '1:1020736520203:web:89f6cf7c60100ecc16470e',
    messagingSenderId: '1020736520203',
    projectId: 'mynotes-midcel',
    authDomain: 'mynotes-midcel.firebaseapp.com',
    storageBucket: 'mynotes-midcel.firebasestorage.app',
  );
}
